# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [8]:
random_list = [float(i) for i in np.random.rand(100)]
print(f"Random list: \n {random_list}")


Random list: 
 [0.8078337554332202, 0.7187865390605346, 0.003919516853492566, 0.9044781259842513, 0.6118881020096233, 0.6248677579716019, 0.2420861301763475, 0.7319116202449067, 0.773217375117452, 0.06825160595918867, 0.892864501122236, 0.01769895451128467, 0.7789573231053515, 0.6914647793627681, 0.8762298201737674, 0.9352602025547517, 0.7321025931019989, 0.6831852115499392, 0.38393364430656496, 0.3898548993010633, 0.6897671954782607, 0.6413208438504833, 0.5943187051052568, 0.8998046735444926, 0.5900223083835378, 0.6251796547817605, 0.4407954846401271, 0.9663327416640012, 0.7487568254289301, 0.9465277076126191, 0.6697767642800443, 0.40359583029478596, 0.5765928276832935, 0.4319029205665339, 0.44873651631761413, 0.5687269147834322, 0.01703315875000533, 0.6705868454810117, 0.8821688085703997, 0.6187253117661655, 0.9895137008503372, 0.7057882687329503, 0.0536831771784585, 0.8610940015866032, 0.4501985254044545, 0.4025580701865755, 0.506578117059773, 0.5510713637255663, 0.6332893642631302,

In [10]:
pwd

'/mnt/c/Users/kevin/Desktop/LaboratoryOfComputationalPhysicsY8/05ex'

In [17]:
file_name = '/mnt/c/Users/kevin/Desktop/LaboratoryOfComputationalPhysicsY8/05ex/simple_data.txt'
with open(file_name, mode='w') as f: # w -> create + overwrite / a -> append on bottom 
    for item in random_list:
        f.write(f"{item} \n")

with open(file_name, mode='r') as f:
    for line in f:
        print(line)

0.8078337554332202 

0.7187865390605346 

0.003919516853492566 

0.9044781259842513 

0.6118881020096233 

0.6248677579716019 

0.2420861301763475 

0.7319116202449067 

0.773217375117452 

0.06825160595918867 

0.892864501122236 

0.01769895451128467 

0.7789573231053515 

0.6914647793627681 

0.8762298201737674 

0.9352602025547517 

0.7321025931019989 

0.6831852115499392 

0.38393364430656496 

0.3898548993010633 

0.6897671954782607 

0.6413208438504833 

0.5943187051052568 

0.8998046735444926 

0.5900223083835378 

0.6251796547817605 

0.4407954846401271 

0.9663327416640012 

0.7487568254289301 

0.9465277076126191 

0.6697767642800443 

0.40359583029478596 

0.5765928276832935 

0.4319029205665339 

0.44873651631761413 

0.5687269147834322 

0.01703315875000533 

0.6705868454810117 

0.8821688085703997 

0.6187253117661655 

0.9895137008503372 

0.7057882687329503 

0.0536831771784585 

0.8610940015866032 

0.4501985254044545 

0.4025580701865755 

0.506578117059773 

0.551071

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [18]:
matrix = np.random.rand(5,5)
print(matrix)

[[0.5914075  0.53171727 0.54691289 0.20008438 0.00527832]
 [0.06557298 0.65723451 0.14488253 0.1680816  0.72449695]
 [0.67327715 0.81164438 0.64657531 0.19376992 0.15563291]
 [0.95375457 0.09752007 0.9490121  0.21915288 0.80802931]
 [0.38764661 0.89321465 0.78201852 0.65306202 0.25334101]]


In [33]:
file_name = '/mnt/c/Users/kevin/Desktop/LaboratoryOfComputationalPhysicsY8/05ex/data.txt'
with open(file_name, mode='w') as f:
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            f.write(f"{str(matrix[i,j])} ") # spacebar to separate
        f.write("\n")

with open(file_name, mode="r") as f:
    for line in f:
        print(line)

0.5914074982278161 0.5317172670837058 0.5469128878865495 0.20008437927391698 0.005278315817286994 

0.06557298312692916 0.6572345074482593 0.14488253387110195 0.16808159637682274 0.7244969549075124 

0.6732771508150013 0.8116443763922281 0.646575305992671 0.19376991667533283 0.15563291251370137 

0.9537545684197699 0.09752006632866939 0.9490121007383299 0.21915287979538367 0.8080293068612883 

0.38764661449567306 0.8932146504973999 0.7820185153878386 0.6530620161290146 0.25334100788374025 



3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [47]:
file_name = '/mnt/c/Users/kevin/Desktop/LaboratoryOfComputationalPhysicsY8/05ex/data.txt'
file_name_csv = '/mnt/c/Users/kevin/Desktop/LaboratoryOfComputationalPhysicsY8/05ex/data.csv'
with open(file_name, mode="r") as txt:
    with open(file_name_csv, mode="w") as csv:
        for line in txt:
            csv.write(f"{line[:-2].replace(" ", ",")}\n") # replace until last 2 letters (" " + "\n") -> dont want line ending with comma
with open(file_name_csv, mode="r") as f:
    for line in f:
        print(line)

0.5914074982278161,0.5317172670837058,0.5469128878865495,0.20008437927391698,0.005278315817286994

0.06557298312692916,0.6572345074482593,0.14488253387110195,0.16808159637682274,0.7244969549075124

0.6732771508150013,0.8116443763922281,0.646575305992671,0.19376991667533283,0.15563291251370137

0.9537545684197699,0.09752006632866939,0.9490121007383299,0.21915287979538367,0.8080293068612883

0.38764661449567306,0.8932146504973999,0.7820185153878386,0.6530620161290146,0.25334100788374025



4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.